name: "Share Player Progression"
description: Share how you trained your player
title: "[Card Type] [Event Type] [Player Name] Training Method"
labels: ["training"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        First off, thanks for taking the time to contribute! Contributions are what make the open-source community such an amazing place to learn, inspire, and create. Any contributions you make will benefit everybody else and are greatly appreciated.
  - type: input
    id: player-card
    attributes:
      label: Player Card Name
      description: >
        Please describe your player card. Otherwise, we may not be able to understand which card you are referring to. Read this to find your Card Type & Event Type.
      placeholder: >
        Example: [Epic] Argentina 2022 | L. Messi
    validations:
      required: true
  - type: textarea
    id: training
    attributes:
      label: Training Method
      description: "Fill the 0's with your progression points"
      value: |
        Shooting: `0`
        Passing: `0`
        Dribbling: `0`
        Dexterity: `0`
        Lower Body Strength: `0`
        Aerial Strength: `0`
        Defending: `0`
        GK 1: `0`
        GK 2: `0`
        GK 3: `0`
      render: bash
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: Screenshot
      description: "Give a screenshot of the player card with progression points applied (if available) to identify it further."
    validations:
      required: true